### ISSUE TITLE
AmazingClientSPA/build is missing

### ISSUE THREAD

**Issue by ghost** [dfrencham/SignalR-Aurelia-Example#1]
As per the title :)

Thanks for making this example

**Comment by dfrencham** [comment]
Added missing files: d98cd6c78f139763a991c1d2febb9db78837c20b

Thanks for letting me know. :)

**Comment by ghost** [comment]
Cheers, I might be making a noob mistake here but I did

npm install
jspm dl-loader
jspm install
gulp build

Viewing the site using visual studio gives

![Error](http://i.imgur.com/pPbtT3G.png)

I suspect its the 

System.config({
       "paths": {
         "_": "dist/_.js"
       }
     });

and the config in config.js conflicting, I tried removing that the above from the index.html and it started loading the libs ok but then failed to load the app js files as it was looking at the root rather than the dist directory.

I then tried merging them to 

  paths: {
    "github:_": "jspm_packages/github/_",
    "npm:_": "jspm_packages/npm/_",
    "_": "dist/_.js"
  },

But that just made the github urls try to usehttp://localhost:2261/dist/github:aurelia/bootstrapper@0.12.0.js etc

A little lost and unsure if I did something wrong, could you let me know?

**Comment by dfrencham** [comment]
There seemed to be some versioning issues going on - Aurelia has had quite a few updates since my initial commit.

I've updated the config.js file (please get latest).

Then try this:
1. Delete your node_modules folder
2. Delete your jspm_packages folder
3. Run **npm install**
4. Run **jspm install**
5. Run **gulp build**

**Do not run jspm dl-loader**

You will get warnings about Babel being unsupported at that version, and that's fine.

At this point, I'm getting an error from Aurelia computed. I'm checking to see if there are further updates I need to make to bring the example into line with the current version of aurelia.

**Comment by dfrencham** [comment]
Ok, there was an explicit import for aurelia-computed - which isn't needed, as it is part of the core aurelia framework now. Hopefully it should work for you now.

**Comment by ghost** [comment]
Working now, great thanks.
